CREATE TABLE accounts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance   DOUBLE PRECISION,
    currency  VARCHAR(255),
    client_id BIGINT,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);

CREATE INDEX accounts_client_id ON accounts (client_id);